# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         hwd
version:      0.18
version_from: HWD.pm
installdirs:  site
requires:
    DateTime:                      0
    DateTime::Format::Strptime:    0
    Getopt::Long:                  0
    Pod::Usage:                    0
    Term::ReadKey:                 0
    Test::Exception:               0
    Test::More:                    0
    Text::CSV_XS:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
